if [ -r /etc/paths ]; then
  # macOS, in /etc/zprofile, uses /usr/lib/path_helper to add items to the path
  # the base paths, in /etc/paths, need to be moved to the beginning of $PATH

  while IFS="" read -r p || [ -n "$p" ]; do
    # remove the item from the path
    path[${path[(i)$p]}]=()

    # append it to the end
    path+=($p)
  done < /etc/paths
fi

if [ -x /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

export NIX_PATH=$HOME/.nix-defexpr/channels

# Ensure NIX_PROFILES is set (needed for non-login shells)
if [[ -z "$NIX_PROFILES" && -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi


# vim: ft=zsh
